CREATE TABLE `Product` (
  `ProductID` varchar(128) NOT NULL,
  `Name` varchar(256) DEFAULT NULL,
  `Description` mediumtext,
  `MerchantCategory` mediumtext,
  `GoogleCategory` varchar(512) DEFAULT NULL,
  `ProductURL` varchar(384) DEFAULT NULL,
  `ImageURL` varchar(300) DEFAULT NULL COMMENT 'Points to S3',
  `AdditionalImageURL` varchar(2048) DEFAULT NULL,
  `ProductCondition` enum('NEW','USED','REFURBISHED') DEFAULT NULL,
  `Price` decimal(10,2) DEFAULT NULL,
  `SalesPrice` decimal(10,2) DEFAULT NULL,
  `Brand` varchar(128) DEFAULT NULL,
  `Manufacturer` varchar(128) DEFAULT NULL,
  `ManufacturerDetails` mediumtext,
  `ManufacturerLocation` varchar(256) DEFAULT NULL,
  `GTIN` varchar(128) DEFAULT NULL,
  `MPN` varchar(128) DEFAULT NULL,
  `Gender` varchar(20) DEFAULT NULL,
  `AgeRangeLow` int(3) DEFAULT NULL,
  `AgeRangeHigh` int(3) DEFAULT NULL,
  `VariantGroupID` varchar(256) DEFAULT NULL,
  `Color` varchar(100) DEFAULT NULL,
  `Size` varchar(45) DEFAULT NULL,
  `Material` varchar(256) DEFAULT NULL,
  `Pattern` varchar(128) DEFAULT NULL,
  `Shipping` varchar(128) DEFAULT NULL,
  `ShippingWeight` varchar(64) DEFAULT NULL,
  `Bundle` varchar(45) DEFAULT NULL,
  `MerchantSKU` varchar(256) DEFAULT NULL,
  `TopSellerRank` int(5) DEFAULT NULL,
  `Tax` varchar(16) DEFAULT NULL,
  `ChannelApplicability` set('ALL','ONLINE','INSTORE','OUTLET','MAIL') DEFAULT NULL,
  `InternalProductID` varchar(128) DEFAULT NULL,
  `PromotionID` varchar(128) DEFAULT NULL,
  `IsDefaultVariant` tinyint(1) DEFAULT '0',
  `ProcessingTime` varchar(32) DEFAULT NULL,
  `Customization` varchar(64) DEFAULT NULL,
  `LastUpdate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Active` tinyint(4) NOT NULL DEFAULT '1',
  `AgeGroup` varchar(20) DEFAULT NULL,
  `Availability` varchar(20) DEFAULT NULL,
  `IsOnSale` tinyint(1) NOT NULL DEFAULT '0',
  `CurrencyCode` char(3) DEFAULT 'USD',
  `PromotionEnd` timestamp NULL DEFAULT NULL,
  `PromotionStart` timestamp NULL DEFAULT NULL,
  `PromotionTitle` varchar(256) DEFAULT NULL,
  `PromotionsMetadata` text,
  `ColorSwatchUrl` varchar(384) DEFAULT NULL,
  `ProductLocation` enum('WEB','STORE','ALL') DEFAULT 'ALL',
  `SalePriceStart` timestamp NULL DEFAULT NULL,
  `SalePriceEnd` timestamp NULL DEFAULT NULL,
  `SizeGuideURL` varchar(256) DEFAULT NULL,
  `SearchImageURL` varchar(256) DEFAULT NULL,
  PRIMARY KEY (`ProductID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
